import Link from "next/link";import {redirect} from "next/navigation";import {getAdminSession,adminGet} from "@/lib/enfoque-admin";
export const dynamic="force-dynamic";
export default async function Admin(){const session=await getAdminSession();if(!session)redirect("/admin/login");const [properties,vehicles,leads]=await Promise.all([
adminGet<any[]>("properties?select=id,title,publication_status,availability,price,currency&order=created_at.desc&limit=8",session.token).catch(()=>[]),
adminGet<any[]>("vehicles?select=id,brand,model,publication_status,availability,price,currency&order=created_at.desc&limit=8",session.token).catch(()=>[]),
adminGet<any[]>("leads?select=id,name,phone,status,channel,created_at&order=created_at.desc&limit=8",session.token).catch(()=>[])
]);return <main className="min-h-screen bg-[#f5f3ee] px-5 py-10"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-black/40">Enfoque Visual</p><h1 className="ev-display mt-2 text-6xl font-black">Panel</h1><p className="mt-2 text-black/50">{session.profile.full_name||session.profile.role}</p></div><form action="/api/enfoque/auth/logout" method="post"><button className="rounded-full bg-black px-5 py-3 text-sm font-bold text-white">Salir</button></form></div>
<div className="mt-10 grid gap-4 md:grid-cols-3"><Link href="/admin/propiedades" className="rounded-3xl bg-white p-6 ring-1 ring-black/5"><b className="text-3xl">{properties.length}</b><p className="mt-2 text-black/50">Propiedades recientes</p></Link><Link href="/admin/vehiculos" className="rounded-3xl bg-white p-6 ring-1 ring-black/5"><b className="text-3xl">{vehicles.length}</b><p className="mt-2 text-black/50">Vehículos recientes</p></Link><Link href="/admin/leads" className="rounded-3xl bg-[#d9ff3f] p-6"><b className="text-3xl">{leads.length}</b><p className="mt-2 text-black/60">Leads recientes</p></Link></div>
<div className="mt-10 grid gap-8 lg:grid-cols-2"><section className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Propiedades</h2><div className="mt-5 space-y-3">{properties.map(p=><div key={p.id} className="flex justify-between border-b border-black/5 pb-3"><span className="font-bold">{p.title}</span><span className="text-xs uppercase text-black/40">{p.publication_status}</span></div>)}</div></section><section className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Leads</h2><div className="mt-5 space-y-3">{leads.map(l=><div key={l.id} className="flex justify-between border-b border-black/5 pb-3"><span className="font-bold">{l.name}</span><span className="text-xs uppercase text-black/40">{l.status}</span></div>)}</div></section></div></div></main>}
