/**
 * Batch verification: imports 40 real .ARW files and checks that the queue,
 * the worker pool and the persistence layer hold up.
 *
 * Also verifies the parts that only appear at scale: duplicate grouping,
 * progress/ETA reporting, and that closing the workspace mid-import does not
 * lose the photos already analysed.
 */
import { readFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Playwright may be installed globally rather than in this repo (the e2e suite
// is not part of `npm ci`), so it is resolved through an env var with a bare
// specifier as the fallback. See tests/e2e/README.md.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? "playwright");

const here = dirname(fileURLToPath(import.meta.url));
const batchDir = join(here, ".artifacts", "batch");
mkdirSync(batchDir, { recursive: true });

let failures = 0;
function check(name, condition, detail = "") {
  const ok = Boolean(condition);
  if (!ok) failures += 1;
  console.log(`${ok ? "PASA " : "FALLA"}  ${name}${detail ? `  -- ${detail}` : ""}`);
}

// The batch is generated by make-batch.mjs: 10 distinct scenes shot as bursts
// of 4, with EXIF timestamps seconds apart inside a burst and minutes apart
// between them. Run `node .verify/make-batch.mjs` to regenerate it.
const files = readdirSync(batchDir)
  .filter((f) => f.endsWith(".ARW"))
  .sort()
  .map((f) => join(batchDir, f));
console.log(`Lote: ${files.length} archivos .ARW`);

const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH,
  args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--no-sandbox"],
});
const context = await browser.newContext({ acceptDownloads: true, viewport: { width: 1400, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => {
  if (m.type() === "error") errors.push(m.text());
});

try {
  await page.goto("http://localhost:3210/studio", { waitUntil: "networkidle" });
  await page.fill('[data-testid="new-project-name"]', "Lote 40");
  await Promise.all([page.waitForURL(/prj_/), page.click('[data-testid="create-project"]')]);
  const projectUrl = page.url();

  const started = Date.now();
  await page.setInputFiles('input[type="file"]', files);

  // The import panel is checked after completion rather than mid-flight: a
  // 40-file batch finishes in seconds, so a mid-flight poll is a race. What
  // matters is that the readouts carry real measured values, not placeholders.
  //
  // Note: the labels are rendered through `text-transform: uppercase`, so
  // innerText returns them capitalised -- match case-insensitively.
  await page.waitForFunction(() => document.body.innerText.includes("terminado"), null, {
    timeout: 900000,
  });
  const elapsed = (Date.now() - started) / 1000;

  const panel = await page.evaluate(() => {
    const text = document.body.innerText;
    return {
      processed: text.match(/PROCESADAS\s*\n\s*(\d+)/i)?.[1],
      rate: text.match(/VELOCIDAD\s*\n\s*([\d.]+)\/s/i)?.[1],
      read: text.match(/LE[IÍ]DO\s*\n\s*([^\n]+)/i)?.[1]?.trim(),
      counter: text.match(/(\d+) de (\d+)/)?.[0],
    };
  });
  check(
    "El panel de importación reporta cifras medidas de verdad",
    panel.processed === "40" && Number(panel.rate) > 0 && /\d/.test(panel.read ?? "") && panel.counter === "40 de 40",
    JSON.stringify(panel),
  );

  const summary = await page.evaluate(async () => {
    const db = await new Promise((r) => {
      const q = indexedDB.open("advibe-photo-studio");
      q.onsuccess = () => r(q.result);
    });
    const readAll = (store) =>
      new Promise((r) => {
        const tx = db.transaction(store, "readonly");
        const q = tx.objectStore(store).getAll();
        q.onsuccess = () => r(q.result);
      });
    const photos = await readAll("photos");
    const groups = await readAll("groups");
    const proxies = await readAll("proxies");
    const thumbs = await readAll("thumbnails");
    const bytes =
      proxies.reduce((s, b) => s + b.size, 0) + thumbs.reduce((s, b) => s + b.size, 0);
    return {
      total: photos.length,
      edited: photos.filter((p) => p.status === "edited").length,
      errors: photos.filter((p) => p.status === "error").map((p) => p.errorMessage),
      groups: groups.length,
      grouped: groups.reduce((s, g) => s + g.photoIds.length, 0),
      groupSizes: groups.map((g) => g.photoIds.length),
      suggestions: groups.filter((g) => g.suggestedId && g.scores[g.suggestedId]).length,
      storedBytes: bytes,
      distinctAdjustments: new Set(
        photos.map((p) => JSON.stringify(p.auto?.adjustments ?? null)),
      ).size,
      hardware: navigator.hardwareConcurrency,
    };
  });

  check("Las 40 se importaron", summary.total === 40, `n=${summary.total}`);
  check("Las 40 quedaron editadas", summary.edited === 40, `editadas=${summary.edited}`);
  check("Ninguna falló", summary.errors.length === 0, summary.errors.slice(0, 3).join(" | "));
  check(
    "Rendimiento razonable en lote",
    elapsed < 180,
    `${elapsed.toFixed(1)} s para 40 (${(40 / elapsed).toFixed(1)}/s, ${summary.hardware} núcleos)`,
  );
  check(
    "Agrupación de duplicados encontró las ráfagas",
    summary.groups >= 8 && summary.grouped >= 32,
    `${summary.groups} grupos, ${summary.grouped} fotos agrupadas, tamaños=${summary.groupSizes.join(",")}`,
  );
  check(
    "Cada grupo trae una recomendación puntuada",
    summary.suggestions === summary.groups,
    `${summary.suggestions}/${summary.groups}`,
  );
  check(
    "El almacenamiento por foto se mantiene acotado",
    summary.storedBytes / 40 < 800_000,
    `${Math.round(summary.storedBytes / 40 / 1024)} KB por fotografía`,
  );

  // Reload: everything analysed must survive, since it is persisted as it goes.
  await page.goto(projectUrl, { waitUntil: "networkidle" });
  await page.waitForTimeout(2500);
  const afterReload = await page.evaluate(() => {
    const text = document.body.innerText;
    const m = text.match(/(\d+) fotograf/);
    return { shown: m?.[1], hasGrid: document.querySelectorAll("img").length };
  });
  check(
    "El trabajo sobrevive a cerrar y reabrir el proyecto",
    afterReload.shown === "40",
    JSON.stringify(afterReload),
  );

  // Groups tab renders the real clusters.
  await page.click('[data-testid="tab-groups"]');
  await page.waitForTimeout(1500);
  const groupsUi = await page.evaluate(() => ({
    labels: [...document.querySelectorAll("h3")].map((h) => h.textContent).filter((t) => t?.startsWith("GRUPO")).length,
    best: document.body.innerText.match(/Mejor/g)?.length ?? 0,
    explains: /nitidez \d+%/.test(document.body.innerText),
  }));
  check("La pestaña Grupos muestra los grupos reales", groupsUi.labels >= 8, JSON.stringify(groupsUi));
  check("Cada grupo explica su recomendación con métricas", groupsUi.explains && groupsUi.best >= 8, JSON.stringify(groupsUi));

  // Batch export: 40 sidecars in one ZIP.
  await page.click('[data-testid="tab-export"]');
  const zipStart = Date.now();
  const [zip] = await Promise.all([
    page.waitForEvent("download", { timeout: 300000 }),
    page.click('button:has-text("Exportar ZIP")'),
  ]);
  const zipPath = join(here, ".artifacts", "downloads", zip.suggestedFilename());
  await zip.saveAs(zipPath);
  const bytes = readFileSync(zipPath);
  const text = bytes.toString("latin1");
  const sidecars = (text.match(/DSC0\d+\.xmp/g) ?? []).length;
  check(
    "El ZIP del lote contiene los 40 sidecars",
    sidecars >= 40,
    `${sidecars} referencias, ${(bytes.length / 1024).toFixed(0)} KB, ${((Date.now() - zipStart) / 1000).toFixed(1)} s`,
  );
} catch (error) {
  check("Ejecucion sin excepciones", false, error.message);
  console.error(error);
} finally {
  check("Sin errores de consola", errors.length === 0, [...new Set(errors)].slice(0, 3).join(" | "));
  await browser.close();
  console.log("");
  console.log(failures === 0 ? "Lote: todo correcto" : `Lote: ${failures} fallo(s)`);
  process.exit(failures > 0 ? 1 : 0);
}
