// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { withDatabaseSchema } from "./lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations target the dedicated "ventads" schema (see lib/database-url.ts).
    url: withDatabaseSchema(process.env["DATABASE_URL"]),
  },
});
