export type Property={id:string;slug:string;title:string;price:number;operation:"venta"|"alquiler";type:string;city:string;sector:string;landM2?:number;buildM2?:number;rooms?:number;baths?:number;parking?:number;description:string;features:string[];images:string[];featured?:boolean};
export type Vehicle={id:string;slug:string;brand:string;model:string;year:number;price:number;mileage:number;fuel:string;transmission:string;engine:string;description:string;features:string[];images:string[];featured?:boolean};
const U=(id:string)=>"https://images.unsplash.com/"+id+"?auto=format&fit=crop&w=1400&q=85";
export const properties:Property[]=[
{id:"p1",slug:"casa-gualaceo-divina-misericordia",title:"Casa contemporánea en Gualaceo",price:190000,operation:"venta",type:"Casa",city:"Gualaceo",sector:"Divina Misericordia",landM2:240,buildM2:210,rooms:4,baths:3,parking:2,description:"Residencia amplia y luminosa, pensada para una familia que busca espacio y tranquilidad.",features:["2 plantas","Patio","Cocina amplia","Área social","2 parqueaderos"],images:[U("photo-1600585154340-be6161a56a0c"),U("photo-1600607687939-ce8a6c25118c"),U("photo-1600566753190-17f0baa2a6c3")],featured:true},
{id:"p2",slug:"departamento-moderno-cuenca",title:"Departamento moderno en Cuenca",price:98000,operation:"venta",type:"Departamento",city:"Cuenca",sector:"El Batán",buildM2:96,rooms:3,baths:2,parking:1,description:"Departamento moderno, cómodo y con excelente distribución.",features:["3 dormitorios","2 baños","Ascensor","Seguridad"],images:[U("photo-1505693416388-ac5ce068fe85"),U("photo-1493809842364-78817add7ffb")],featured:true},
{id:"p3",slug:"terreno-ricaurte",title:"Terreno para proyecto en Ricaurte",price:65000,operation:"venta",type:"Terreno",city:"Cuenca",sector:"Ricaurte",landM2:520,description:"Terreno con potencial para vivienda o proyecto inmobiliario.",features:["520 m²","Zona residencial","Acceso vehicular","Servicios cercanos"],images:[U("photo-1500382017468-9049fed747ef")],featured:true},
{id:"p4",slug:"departamento-alquiler-centro-cuenca",title:"Departamento en alquiler",price:550,operation:"alquiler",type:"Departamento",city:"Cuenca",sector:"Centro",buildM2:82,rooms:2,baths:2,parking:1,description:"Departamento práctico y bien ubicado.",features:["2 dormitorios","2 baños","Amoblado","Parqueadero"],images:[U("photo-1522708323590-d24dbb6b0267")]}
];
export const vehicles:Vehicle[]=[
{id:"v1",slug:"mini-cooper-s-2020",brand:"MINI",model:"Cooper S",year:2020,price:28900,mileage:42000,fuel:"Gasolina",transmission:"Automática",engine:"2.0 Turbo",description:"MINI Cooper S con presencia, desempeño y equipamiento.",features:["Techo panorámico","Pantalla multimedia","Cámara","Modo Sport"],images:[U("photo-1492144534655-ae79c964c9d7"),U("photo-1503736334956-4c8f8e92946d")],featured:true},
{id:"v2",slug:"toyota-fortuner-2022",brand:"Toyota",model:"Fortuner",year:2022,price:46500,mileage:31000,fuel:"Diésel",transmission:"Automática",engine:"2.8 Turbo",description:"SUV familiar y robusta.",features:["7 pasajeros","4x4","Cámara","Control crucero"],images:[U("photo-1549317661-bd32c8ce0db2")],featured:true}
];
export const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
export const getProperty=(slug:string)=>properties.find(x=>x.slug===slug);
export const getVehicle=(slug:string)=>vehicles.find(x=>x.slug===slug);