"use client";
import {useState} from "react";
type ImageItem={id:string;storage_path:string;is_cover:boolean;sort_order:number};
export function AdminImages({listingId,type,initial}:{listingId:string;type:"property"|"vehicle";initial:ImageItem[]}){const [images,setImages]=useState(initial);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 const url=(p:string)=>`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/listing-media/${p}`;
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMsg("Subiendo…");const fd=new FormData();fd.append("file",file);fd.append(type==="property"?"property_id":"vehicle_id",listingId);const r=await fetch("/api/enfoque/admin/listing-images",{method:"POST",body:fd});const d=await r.json();if(r.ok)setImages(x=>[...x,d.item]);setMsg(r.ok?"Imagen subida.":d.error||"Error");setBusy(false);e.target.value=""}
 async function remove(id:string){if(!confirm("¿Eliminar esta imagen?"))return;const r=await fetch("/api/enfoque/admin/listing-images",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok)setImages(x=>x.filter(i=>i.id!==id));}
 async function cover(id:string){const r=await fetch("/api/enfoque/admin/listing-images/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_cover:true})});if(r.ok)setImages(x=>x.map(i=>({...i,is_cover:i.id===id})))}
 return <section className="mt-8 rounded-3xl bg-white p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Fotografías</h2><p className="text-sm text-black/50">Máximo 8 MB por imagen. Marca una como portada.</p></div><label className="cursor-pointer rounded-full bg-black px-5 py-3 text-sm font-bold text-white">{busy?"Subiendo…":"+ Añadir foto"}<input disabled={busy} type="file" accept="image/*" onChange={upload} className="hidden"/></label></div><div className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4">{images.map(i=><div key={i.id} className="overflow-hidden rounded-2xl bg-black/5"><img src={url(i.storage_path)} alt="" className="aspect-square w-full object-cover"/><div className="flex gap-2 p-2"><button onClick={()=>cover(i.id)} className={"flex-1 rounded-lg px-2 py-2 text-xs font-bold "+(i.is_cover?"bg-[#d9ff3f]":"bg-black/5")}>{i.is_cover?"Portada":"Hacer portada"}</button><button onClick={()=>remove(i.id)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">×</button></div></div>)}</div>{!images.length&&<p className="mt-5 rounded-2xl bg-black/5 p-5 text-sm text-black/50">Todavía no hay fotografías.</p>}{msg&&<p className="mt-4 text-sm font-bold">{msg}</p>}</section>}
