import Link from "next/link";import {Property,Vehicle,money} from "@/lib/enfoque-data";import {label} from "@/lib/enfoque-filters";import {ListingImage} from "./ListingImage";
function Cover({src,alt}:{src?:string;alt:string}){return src?<ListingImage src={src} alt={alt} sizes="(min-width:1024px) 33vw, (min-width:768px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-105"/>:<div className="flex h-full flex-col items-center justify-center gap-2 bg-[#e8e5dd] text-black/35"><span className="text-3xl">◎</span><span className="text-xs font-bold uppercase tracking-[.16em]">Fotos pronto</span></div>}
function Badges({operation,availability,video}:{operation?:string;availability?:string;video?:string}){return <div className="absolute left-3 top-3 flex flex-wrap gap-1.5">{operation&&<span className="rounded-full bg-white/95 px-3 py-1 text-[11px] font-black uppercase tracking-wide shadow-sm">{label(operation)}</span>}{availability&&availability!=="disponible"&&<span className="rounded-full bg-black px-3 py-1 text-[11px] font-black uppercase tracking-wide text-white">{label(availability)}</span>}{video&&<span className="rounded-full bg-[#d9ff3f] px-3 py-1 text-[11px] font-black uppercase tracking-wide">▶ Video</span>}</div>}
function PhotoCount({n}:{n:number}){return n>1?<span className="absolute bottom-3 right-3 rounded-full bg-black/70 px-2.5 py-1 text-[11px] font-bold text-white backdrop-blur">{n} fotos</span>:null}
function Specs({items}:{items:(string|false|undefined|null)[]}){const xs=items.filter(Boolean) as string[];return xs.length?<ul className="mt-4 flex flex-wrap gap-1.5">{xs.map(s=><li key={s} className="rounded-full bg-[#f5f3ee] px-2.5 py-1 text-[11px] font-bold text-black/65">{s}</li>)}</ul>:null}
function Footer({where}:{where:string}){return <div className="mt-5 flex items-center justify-between gap-3 border-t border-black/5 pt-4 text-sm"><span className="truncate text-black/50">{where}</span><span className="shrink-0 font-black transition group-hover:translate-x-0.5">Ver ficha →</span></div>}
export function PropertyCard({x}:{x:Property}){return <Link href={"/enfoque-visual/propiedades/"+x.slug} className="ev-card group flex flex-col transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden"><Cover src={x.images[0]} alt={x.title}/><Badges operation={x.operation} availability={x.availability} video={x.video}/><PhotoCount n={x.images.length}/></div><div className="flex flex-1 flex-col p-5"><p className="text-[11px] font-black uppercase tracking-[.16em] text-black/40">{label(x.type)}</p><div className="mt-1 text-2xl font-black">{money(x.price)}{x.operation==="alquiler"&&<small className="text-sm font-medium text-black/45">/mes</small>}</div><h3 className="mt-1 text-lg font-bold leading-snug">{x.title}</h3><Specs items={[x.rooms?x.rooms+" hab.":null,x.baths?x.baths+" baños":null,x.buildM2?x.buildM2+" m²":null,x.landM2?x.landM2+" m² terreno":null,x.parking?x.parking+" parq.":null]}/><div className="mt-auto"><Footer where={[x.city,x.sector].filter(Boolean).join(" · ")}/></div></div></Link>}
export function VehicleCard({x}:{x:Vehicle}){return <Link href={"/enfoque-visual/vehiculos/"+x.slug} className="ev-card group flex flex-col transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden"><Cover src={x.images[0]} alt={x.brand+" "+x.model}/><Badges availability={x.availability} video={x.video}/><PhotoCount n={x.images.length}/></div><div className="flex flex-1 flex-col p-5"><p className="text-[11px] font-black uppercase tracking-[.16em] text-black/40">{x.brand} · {x.year}</p><div className="mt-1 text-2xl font-black">{money(x.price)}</div><h3 className="mt-1 text-lg font-bold leading-snug">{x.brand} {x.model}</h3><Specs items={[x.mileage.toLocaleString("es-EC")+" km",x.fuel&&label(x.fuel),x.transmission&&label(x.transmission),x.engine]}/><div className="mt-auto"><Footer where={x.city||"Ecuador"}/></div></div></Link>}
export function EmptyResults({href,filtered}:{href:string;filtered:boolean}){return <div className="mt-10 rounded-3xl bg-white p-10 text-center ring-1 ring-black/5"><p className="text-xl font-black">{filtered?"No hay resultados con esos filtros.":"Pronto tendremos publicaciones aquí."}</p><p className="mt-2 text-sm text-black/50">{filtered?"Prueba con menos filtros o cuéntanos qué buscas.":"Cuéntanos qué buscas y te avisamos."}</p><div className="mt-6 flex justify-center gap-3">{filtered&&<Link href={href} className="rounded-full bg-black/5 px-5 py-3 text-sm font-bold">Ver todo</Link>}<Link href="/enfoque-visual/contacto" className="rounded-full bg-black px-5 py-3 text-sm font-bold text-white">Contactar</Link></div></div>}
